dist: trusty

language: python

cache:
  directories:
  - /home/travis/download
  - /home/travis/.cache/pip

# This matrix tests that the code works on Python 2.7,
# 3.5, 3.6 (same versions as PyTorch CI), and passes lint.
matrix:
  fast_finish: true
  include:
    - env: PYTHON_VERSION="2.7" COVERAGE="true"
    - env: PYTHON_VERSION="3.5" COVERAGE="true"
    - env: PYTHON_VERSION="3.6" COVERAGE="true"
    - env: PYTHON_VERSION="2.7" RUN_FLAKE8="true" SKIP_TESTS="true"
    - env: PYTHON_VERSION="3.6" RUN_FLAKE8="true" SKIP_TESTS="true"
    - env: PYTHON_VERSION="2.7" RUN_SLOW="true" COVERAGE="true"
      sudo: required
    - env: PYTHON_VERSION="3.6" RUN_SLOW="true" COVERAGE="true"
      sudo: required
  allow_failures:
    - env: PYTHON_VERSION="2.7" RUN_SLOW="true" COVERAGE="true"
    - env: PYTHON_VERSION="3.6" RUN_SLOW="true" COVERAGE="true"

notifications:
  email: false

before_install:
  - export CXX="g++-6" CC="gcc-6"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      
install: source build_tools/travis/install.sh
script: bash build_tools/travis/test_script.sh
after_success: source build_tools/travis/after_success.sh
