dist: trusty

language: python

cache:
  directories:
  - /home/travis/download
  - /home/travis/.cache/pip

# This matrix tests that the code works on Python 2.7,
# 2.7.9, 3.5, 3.6 (same versions as PyTorch CI), and passes lint.
matrix:
  fast_finish: true
  include:
    - env: PYTHON_VERSION="2.7" COVERAGE="true"
    - env: PYTHON_VERSION="2.7.9" COVERAGE="true"
    - env: PYTHON_VERSION="3.5" COVERAGE="true"
    - env: PYTHON_VERSION="3.6" COVERAGE="true"
    - env: PYTHON_VERSION="2.7" RUN_FLAKE8="true" SKIP_TESTS="true"
    - env: PYTHON_VERSION="3.6" RUN_FLAKE8="true" SKIP_TESTS="true"
notifications:
  email: false

install: source build_tools/travis/install.sh
script: bash build_tools/travis/test_script.sh
after_success: source build_tools/travis/after_success.sh
