channels:
  - defaults
dependencies:
  - flake8==3.7.9
  - codecov
  - pip
  - pip:
    - dataclasses
    - nltk
    - requests
    - revtok
    - pytest
    - pytest-cov
    - pytest-pythonpath
    - sacremoses
    - spacy
    - sphinx
    - sphinx-rtd-theme
    - tqdm
    - sentencepiece
    - certifi
    - future
    - https://github.com/explosion/spacy-models/releases/download/de_core_news_sm-2.2.5/de_core_news_sm-2.2.5.tar.gz#egg=de_core_news_sm==2.2.5
    - https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.2.5/en_core_web_sm-2.2.5.tar.gz#egg=en_core_web_sm==2.2.5
